/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.68
 * Generated at: 2022-11-15 02:33:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.*;
import java.util.ArrayList;

public final class art_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("model");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");


String associatesOn = (String) request.getAttribute("associatesOn");

String checkedIds[] = (String[]) request.getAttribute("checkedIds");
	 
String checkedNames[] = (String[]) request.getAttribute("checkedNames");

ArrayList<Arts> listArt = (ArrayList<Arts>) request.getAttribute("Art");


      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html id=\"html5\" lang=\"en-US\">\r\n");
      out.write("\r\n");
      out.write("    <head>\r\n");
      out.write("\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/art.css\" />\r\n");
      out.write("\r\n");
      out.write("        <title>WODA</title>\r\n");
      out.write("\r\n");
      out.write("        <link rel=\"icon\" href=\"images/logos/LogoWODA2.png\" type=\"image/gif\">\r\n");
      out.write("\r\n");
      out.write("    </head>\r\n");
      out.write("\r\n");
      out.write("    <!-- \r\n");
      out.write("    <section id=\"statusSistema\">\r\n");
      out.write("\r\n");
      out.write("    </section>\r\n");
      out.write("     -->\r\n");
      out.write("\r\n");
      out.write("    <header>\r\n");
      out.write("\r\n");
      out.write("        <section id=\"sectionMenu\">\r\n");
      out.write("\r\n");
      out.write("            <section id=\"sectionButtons\">\r\n");
      out.write("\r\n");
      out.write("                <button type=\"button\" id=\"seacherButton\" class=\"Buttons\">\r\n");
      out.write("\r\n");
      out.write("                    <img class=\"ImagesButtons\" id=\"imageSeacherButton\" src=\"images/icons/voltar.png\" alt=\"\"\r\n");
      out.write("                        onclick=\"openPage('main', '_self')\">\r\n");
      out.write("\r\n");
      out.write("                </button>\r\n");
      out.write("\r\n");
      out.write("                <button type=\"button\" id=\"infoButton\" class=\"Buttons\">\r\n");
      out.write("\r\n");
      out.write("                    <img class=\"ImagesButtons\" id=\"imageInfoButton\" src=\"images/icons/info.png\" alt=\"\"\r\n");
      out.write("                        onclick=\"openClose(info,'display','menuInfo')\">\r\n");
      out.write("\r\n");
      out.write("                </button>\r\n");
      out.write("\r\n");
      out.write("            </section>\r\n");
      out.write("\r\n");
      out.write("            <section id=\"sectionMenuButton\">\r\n");
      out.write("\r\n");
      out.write("                <button type=\"button\" id=\"buttonMenu\">\r\n");
      out.write("\r\n");
      out.write("                    <img id=\"imagemButtonMenu\" src=\"images/icons/menu01.png\" alt=\"\"\r\n");
      out.write("                        onclick=\"openClose(sectionButtons,'visibility')\">\r\n");
      out.write("\r\n");
      out.write("                </button>\r\n");
      out.write("\r\n");
      out.write("            </section>\r\n");
      out.write("\r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <body>\r\n");
      out.write("\r\n");
      out.write("        <section class=\"SectionArtsArtist\">\r\n");
      out.write("\r\n");
      out.write("            <!-- ARTS 1 -->\r\n");
      out.write("\r\n");
      out.write("            <section id=\"artArtist\" class=\"ArtsArtist\">\r\n");
      out.write("\r\n");
      out.write("                <section id=\"buttonsZoom\">\r\n");
      out.write("\r\n");
      out.write("                    <section class=\"TitlesAuthor\">\r\n");
      out.write("                     ");
out.print(request.getAttribute("nameArt"));
      out.write("\r\n");
      out.write("                    </section>\r\n");
      out.write("\r\n");
      out.write("                </section>\r\n");
      out.write("\r\n");
      out.write("                <section id=\"buttonsZoom\">\r\n");
      out.write("\r\n");
      out.write("                    <section class=\"EditButtonsSection\">\r\n");
      out.write("\r\n");
      out.write("                        <section id=\"sectionButtonsArtist\">\r\n");
      out.write("\r\n");
      out.write("                            <button type=\"button\" id=\"editButton\" class=\"Buttons\" onclick=\"openPage('artedit','_self')\">\r\n");
      out.write("\r\n");
      out.write("                                <img class=\"ImagesButtons\" id=\"imageEditButton\" src=\"images/icons/editar03.png\"\r\n");
      out.write("                                    alt=\"\">\r\n");
      out.write("\r\n");
      out.write("                            </button>\r\n");
      out.write("\r\n");
      out.write("                        </section>\r\n");
      out.write("\r\n");
      out.write("                        <section id=\"sectionButtonsArtist\">\r\n");
      out.write("\r\n");
      out.write("                            <button type=\"button\" id=\"editButton\" class=\"Buttons\" onclick=\"openPage('deleteArt?idArt=','_self')\">\r\n");
      out.write("\r\n");
      out.write("                                <img class=\"ImagesButtons\" id=\"imageEditButton\" src=\"images/icons/deletar01Vazio.png\"\r\n");
      out.write("                                    alt=\"\">\r\n");
      out.write("\r\n");
      out.write("                            </button>\r\n");
      out.write("\r\n");
      out.write("                        </section>\r\n");
      out.write("\r\n");
      out.write("                    </section>\r\n");
      out.write("\r\n");
      out.write("                </section>\r\n");
      out.write("\r\n");
      out.write("                <section class=\"TitlesArts\">\r\n");
      out.write("\r\n");
      out.write("                    <section class=\"TitlesNames\">ART:\r\n");
      out.write("\r\n");
      out.write("                        <section class=\"Data\">\r\n");
      out.write("						\r\n");
      out.write("						       ");
out.print(request.getAttribute("nameArt"));
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        </section>\r\n");
      out.write("\r\n");
      out.write("                    </section>\r\n");
      out.write("\r\n");
      out.write("                    <section class=\"TitlesNames\">\r\n");
      out.write("                        <h3>DESCRIPTION:</h3>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        <p class=\"TextDescription\">\r\n");
      out.write("                               ");
out.print(request.getAttribute("description"));
      out.write("\r\n");
      out.write("                        </p>\r\n");
      out.write("\r\n");
      out.write("                    </section>\r\n");
      out.write("\r\n");
      out.write("                    <section class=\"TitlesNames\">\r\n");
      out.write("                        EXHIBITION DATE:\r\n");
      out.write("\r\n");
      out.write("                        <section class=\"Data\">\r\n");
      out.write("                           ");
out.print(request.getAttribute("exposuredate"));
      out.write("\r\n");
      out.write("                        </section>\r\n");
      out.write("\r\n");
      out.write("                    </section>\r\n");
      out.write("\r\n");
      out.write("                    <section class=\"TitlesNames\">\r\n");
      out.write("                        PUBLICATION DATE:\r\n");
      out.write("\r\n");
      out.write("                        <section class=\"Data\">\r\n");
      out.write("                            ");
out.print(request.getAttribute("publicationdate"));
      out.write("\r\n");
      out.write("                        </section>\r\n");
      out.write("\r\n");
      out.write("                    </section>\r\n");
      out.write("\r\n");
      out.write("                    <section class=\"TitlesNames\">\r\n");
      out.write("\r\n");
      out.write("                        ARTIST'S:\r\n");
      out.write("\r\n");
      out.write("                        <section class=\"ArtistsExtras\">\r\n");
      out.write("\r\n");
      out.write("							<section class=\"ArtistsExtras\">   \r\n");
      out.write("							\r\n");
      out.write("								<a href=\"artist?idArtist=");
out.print(request.getAttribute("idArtist"));
      out.write("\">\r\n");
      out.write("                        			");
out.print(request.getAttribute("nameArtist"));
      out.write("\r\n");
      out.write("								</a>                               				                   				        \r\n");
      out.write("                        	\r\n");
      out.write("                        	</section>	\r\n");
      out.write("\r\n");
      out.write("						");
if(associatesOn.equals("YES"))
  						{

   							for (int i = 0; i < checkedIds.length; i++)   
                        	{                       	
                        	
      out.write(" \r\n");
      out.write("								<section class=\"ArtistsExtras\">   \r\n");
      out.write("							\r\n");
      out.write("									<a href=\"artist?idArtist=\r\n");
      out.write("									");
 if(associatesOn.equals("YES"))
  										 {
      out.write("\r\n");
      out.write("											");
      out.print(checkedIds[i]);
      out.write("\">\r\n");
      out.write("  										 \r\n");
      out.write("                        					");
      out.print(checkedNames[i]);
      out.write("\r\n");
      out.write("									");
   }
      out.write("\r\n");
      out.write("									</a>                               				                   				        \r\n");
      out.write("                        	\r\n");
      out.write("                       		 	</section>	            \r\n");
      out.write("                        	");
	
                         	}
  						}
                   			
      out.write("                 \r\n");
      out.write("   \r\n");
      out.write("                        </section>\r\n");
      out.write("\r\n");
      out.write("                    </section>\r\n");
      out.write("\r\n");
      out.write("                </section>\r\n");
      out.write("\r\n");
      out.write("            </section>\r\n");
      out.write("\r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("        <section id=\"info\">\r\n");
      out.write("\r\n");
      out.write("            Dev - Paulo de Tasso <br>\r\n");
      out.write("            Senior Full Stack Developer <br>\r\n");
      out.write("            World of digital artists - WODA®\r\n");
      out.write("\r\n");
      out.write("            <img class=\"ImagesButtons\" src=\"images/icons/SUPORTE01.png\" alt=\"\">\r\n");
      out.write("\r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("    </body>\r\n");
      out.write("\r\n");
      out.write("    <!--  \r\n");
      out.write("    <div class=\"load\">\r\n");
      out.write("        <div class=\"dot\"></div>\r\n");
      out.write("        <div class=\"dot\"></div>\r\n");
      out.write("        <div class=\"dot\"></div>\r\n");
      out.write("        <div class=\"dot\"></div>\r\n");
      out.write("        <div class=\"dot\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("    -->\r\n");
      out.write("\r\n");
      out.write("    <footer>\r\n");
      out.write("\r\n");
      out.write("        <section id=\"sectionFooter\">\r\n");
      out.write("\r\n");
      out.write("            World of digital artists - WODA®\r\n");
      out.write("\r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"js/artist.js\">\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"js/validator.js\">\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
