/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.68
 * Generated at: 2022-11-15 20:34:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.*;
import java.util.ArrayList;

public final class artist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("model");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");

 ArrayList<Arts> listAllArtsArtist = (ArrayList<Arts>) request.getAttribute("listAllArtsArtist");  

String dataDeExposicao;

String dataDePublicacao;


      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html id=\"html5\" lang=\"en-US\">\r\n");
      out.write("\r\n");
      out.write("    <head>\r\n");
      out.write("\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/artist.css\" />\r\n");
      out.write("\r\n");
      out.write("        <title>WODA</title>\r\n");
      out.write("\r\n");
      out.write("        <link rel=\"icon\" href=\"images/logos/LogoWODA2.png\" type=\"image/gif\">\r\n");
      out.write("\r\n");
      out.write("    </head>\r\n");
      out.write("\r\n");
      out.write("    <!-- \r\n");
      out.write("    <section id=\"statusSistema\">\r\n");
      out.write("\r\n");
      out.write("    </section>\r\n");
      out.write("     -->\r\n");
      out.write("\r\n");
      out.write("    <header>\r\n");
      out.write("\r\n");
      out.write("        <section id=\"sectionMenu\">\r\n");
      out.write("\r\n");
      out.write("            <section id=\"sectionButtons\">\r\n");
      out.write("\r\n");
      out.write("                <button type=\"button\" id=\"seacherButton\" class=\"Buttons\">\r\n");
      out.write("\r\n");
      out.write("                    <img class=\"ImagesButtons\" id=\"imageSeacherButton\" src=\"images/icons/voltar.png\" alt=\"\"\r\n");
      out.write("                        onclick=\"openPage('main', '_self')\">\r\n");
      out.write("\r\n");
      out.write("                </button>\r\n");
      out.write("\r\n");
      out.write("                <button type=\"button\" id=\"infoButton\" class=\"Buttons\">\r\n");
      out.write("\r\n");
      out.write("                    <img class=\"ImagesButtons\" id=\"imageInfoButton\" src=\"images/icons/info.png\" alt=\"\"\r\n");
      out.write("                        onclick=\"openClose(info,'display','menuInfo')\">\r\n");
      out.write("\r\n");
      out.write("                </button>\r\n");
      out.write("\r\n");
      out.write("            </section>\r\n");
      out.write("\r\n");
      out.write("            <section id=\"sectionMenuButton\">\r\n");
      out.write("\r\n");
      out.write("                <button type=\"button\" id=\"buttonMenu\">\r\n");
      out.write("\r\n");
      out.write("                    <img id=\"imagemButtonMenu\" src=\"images/icons/menu01.png\" alt=\"\"\r\n");
      out.write("                        onclick=\"openClose(sectionButtons,'visibility')\">\r\n");
      out.write("\r\n");
      out.write("                </button>\r\n");
      out.write("\r\n");
      out.write("            </section>\r\n");
      out.write("\r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <body>\r\n");
      out.write("\r\n");
      out.write("        <section id=\"sectionArtist\">\r\n");
      out.write("\r\n");
      out.write("            <!-- ARTIST -->\r\n");
      out.write("\r\n");
      out.write("            <section class=\"SectionArtistArts\">\r\n");
      out.write("\r\n");
      out.write("                <section class=\"buttonsZoom\">                   \r\n");
      out.write("\r\n");
      out.write("                    <section class=\"TitlesAuthor\">\r\n");
      out.write("                       ");
out.print(request.getAttribute("name"));
      out.write("\r\n");
      out.write("                    </section>\r\n");
      out.write("\r\n");
      out.write("                </section>\r\n");
      out.write("\r\n");
      out.write("                <section class=\"SectionImageArtist\">\r\n");
      out.write("\r\n");
      out.write("                    <section class=\"buttonsZoom\">\r\n");
      out.write("\r\n");
      out.write("                        <section class=\"EditButtonsSection\">\r\n");
      out.write("\r\n");
      out.write("                            <section>\r\n");
      out.write("\r\n");
      out.write("                                <button type=\"button\" class=\"Buttons\" onclick=\"openPage('selectartistedit?idArtist=");
out.print(request.getAttribute("idArtist"));
      out.write("','_self')\">\r\n");
      out.write("\r\n");
      out.write("                                    <img class=\"ImagesButtons\" src=\"images/icons/editar03.png\"\r\n");
      out.write("                                        alt=\"\">\r\n");
      out.write("\r\n");
      out.write("                                </button>\r\n");
      out.write("\r\n");
      out.write("                            </section>\r\n");
      out.write("\r\n");
      out.write("                            <section>\r\n");
      out.write("\r\n");
      out.write("                                <button type=\"button\" class=\"Buttons\" onclick=\"openPage('javascript: confirmar(");
out.print(request.getAttribute("idArtist"));
      out.write(")','_self')\">\r\n");
      out.write("\r\n");
      out.write("                                    <img class=\"ImagesButtons\"\r\n");
      out.write("                                        src=\"images/icons/deletar01Vazio.png\" alt=\"\">\r\n");
      out.write("\r\n");
      out.write("                                </button>\r\n");
      out.write("\r\n");
      out.write("                            </section>\r\n");
      out.write("\r\n");
      out.write("                        </section>\r\n");
      out.write("\r\n");
      out.write("                    </section>\r\n");
      out.write("\r\n");
      out.write("                    <section class=\"SectionAuthorArts\">\r\n");
      out.write("\r\n");
      out.write("                        <section class=\"SectionDataArtist\">\r\n");
      out.write("\r\n");
      out.write("                            <section class=\"DataTitlesArtist\">\r\n");
      out.write("\r\n");
      out.write("                                <section class=\"TitlesArtist\">\r\n");
      out.write("\r\n");
      out.write("                                    ARTIST:\r\n");
      out.write("\r\n");
      out.write("                                </section>\r\n");
      out.write("\r\n");
      out.write("                                <section class=\"DataArtist\" onclick=\"openPage('artist.html','_self')\">\r\n");
      out.write("                                      ");
out.print(request.getAttribute("name"));
      out.write("\r\n");
      out.write("                                </section>\r\n");
      out.write("\r\n");
      out.write("                            </section>\r\n");
      out.write("\r\n");
      out.write("                            <section class=\"DataTitlesArtist\">\r\n");
      out.write("\r\n");
      out.write("                                <section class=\"TitlesArtist\">\r\n");
      out.write("\r\n");
      out.write("                                    GENDER:\r\n");
      out.write("\r\n");
      out.write("                                </section>\r\n");
      out.write("\r\n");
      out.write("                                <section class=\"DataArtist\">\r\n");
      out.write("\r\n");
      out.write("                                      ");
out.print(request.getAttribute("gender"));
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                </section>\r\n");
      out.write("\r\n");
      out.write("                            </section>\r\n");
      out.write("\r\n");
      out.write("                            <section class=\"DataTitlesArtist\">\r\n");
      out.write("\r\n");
      out.write("                                <section class=\"TitlesArtist\">\r\n");
      out.write("\r\n");
      out.write("                                    E-MAIL:\r\n");
      out.write("\r\n");
      out.write("                                </section>\r\n");
      out.write("\r\n");
      out.write("                                <section class=\"DataArtist\">\r\n");
      out.write("\r\n");
      out.write("                                     ");
out.print(request.getAttribute("email"));
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                </section>\r\n");
      out.write("\r\n");
      out.write("                            </section>\r\n");
      out.write("\r\n");
      out.write("                            <section class=\"DataTitlesArtist\">\r\n");
      out.write("\r\n");
      out.write("                                <section class=\"TitlesArtist\">\r\n");
      out.write("\r\n");
      out.write("                                    BIRTH DATE:\r\n");
      out.write("\r\n");
      out.write("                                </section>\r\n");
      out.write("\r\n");
      out.write("                                <section class=\"DataArtist\">\r\n");
      out.write("\r\n");
      out.write("                                     ");
out.print(request.getAttribute("birthday"));
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                </section>\r\n");
      out.write("\r\n");
      out.write("                            </section>\r\n");
      out.write("\r\n");
      out.write("                            <section class=\"DataTitlesArtist\">\r\n");
      out.write("\r\n");
      out.write("                                <section class=\"TitlesArtist\">\r\n");
      out.write("\r\n");
      out.write("                                    NATIONALITY:\r\n");
      out.write("\r\n");
      out.write("                                </section>\r\n");
      out.write("\r\n");
      out.write("                                <section class=\"DataArtist\">\r\n");
      out.write("\r\n");
      out.write("                                      ");
out.print(request.getAttribute("nationality"));
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                </section>\r\n");
      out.write("\r\n");
      out.write("                            </section>\r\n");
      out.write("\r\n");
      out.write("                            <section class=\"DataTitlesArtist\">\r\n");
      out.write("\r\n");
      out.write("                                <section class=\"TitlesArtist\">\r\n");
      out.write("\r\n");
      out.write("                                    CPF:\r\n");
      out.write("\r\n");
      out.write("                                </section>\r\n");
      out.write("\r\n");
      out.write("                                <section class=\"DataArtist\">\r\n");
      out.write("\r\n");
      out.write("                                      ");
out.print(request.getAttribute("cpf"));
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                </section>\r\n");
      out.write("\r\n");
      out.write("                            </section>\r\n");
      out.write("\r\n");
      out.write("                        </section>\r\n");
      out.write("\r\n");
      out.write("                    </section>\r\n");
      out.write("\r\n");
      out.write("                </section>\r\n");
      out.write("\r\n");
      out.write("                <!-- ADD ARTS -->\r\n");
      out.write("\r\n");
      out.write("                <section id=\"sectionRegisterButtons\">\r\n");
      out.write("\r\n");
      out.write("                    <section class=\"TitlesNames\">                        \r\n");
      out.write("\r\n");
      out.write("                        <button type=\"button\" class=\"Buttons\" onclick=\"openPage('addart?idArtist=");
out.print(request.getAttribute("idArtist")); 
      out.write("','_self')\">\r\n");
      out.write("\r\n");
      out.write("                            <img class=\"ImagesButtons\" id=\"imageRegisterButton\" src=\"images/icons/cadastrar.png\"\r\n");
      out.write("                                alt=\"\">\r\n");
      out.write("\r\n");
      out.write("                        </button>\r\n");
      out.write("\r\n");
      out.write("                    </section>\r\n");
      out.write("\r\n");
      out.write("                </section>\r\n");
      out.write("\r\n");
      out.write("                <section class=\"SectionArtsArtist\">       		      			\r\n");
      out.write("       			\r\n");
      out.write(" 					<!-- ART -->\r\n");
      out.write("\r\n");
      out.write(" 					");
for (int i=0; i < listAllArtsArtist.size(); i++)
                	{    
               		
      out.write("\r\n");
      out.write(" 				\r\n");
      out.write("                    <section class=\"ArtsArtist\">\r\n");
      out.write("\r\n");
      out.write("                        <section class=\"buttonsZoom\">\r\n");
      out.write("\r\n");
      out.write("                            <section class=\"TitlesAuthor\">\r\n");
      out.write("                               ");
      out.print(listAllArtsArtist.get(i).getName());
      out.write("\r\n");
      out.write("                            </section>\r\n");
      out.write("\r\n");
      out.write("                        </section>\r\n");
      out.write("\r\n");
      out.write("                        <section class=\"buttonsZoom\">\r\n");
      out.write("\r\n");
      out.write("                            <section class=\"EditButtonsSection\">\r\n");
      out.write("\r\n");
      out.write("                                <section>\r\n");
      out.write("\r\n");
      out.write("                                    <button type=\"button\" class=\"Buttons\">\r\n");
      out.write("\r\n");
      out.write("                                        <img class=\"ImagesButtons\" \r\n");
      out.write("                                            src=\"images/icons/editar03.png\" alt=\"\">\r\n");
      out.write("\r\n");
      out.write("                                    </button>\r\n");
      out.write("\r\n");
      out.write("                                </section>\r\n");
      out.write("\r\n");
      out.write("                                <section>\r\n");
      out.write("\r\n");
      out.write("                                    <button type=\"button\" class=\"Buttons\">\r\n");
      out.write("\r\n");
      out.write("                                        <img class=\"ImagesButtons\"\r\n");
      out.write("                                            src=\"images/icons/deletar01Vazio.png\" alt=\"\">\r\n");
      out.write("\r\n");
      out.write("                                    </button>\r\n");
      out.write("\r\n");
      out.write("                                </section>\r\n");
      out.write("\r\n");
      out.write("                            </section>\r\n");
      out.write("\r\n");
      out.write("                        </section>\r\n");
      out.write("\r\n");
      out.write("                        <section class=\"TitlesArts\">\r\n");
      out.write("\r\n");
      out.write("                            <section class=\"TitlesNames\">\r\n");
      out.write("                            \r\n");
      out.write("                            	ART:\r\n");
      out.write("\r\n");
      out.write("                                <section class=\"Names\">\r\n");
      out.write("\r\n");
      out.write("									<a href=\"art?idart=");
      out.print(listAllArtsArtist.get(i).getIdart());
      out.write("\">\r\n");
      out.write("                               			");
      out.print(listAllArtsArtist.get(i).getName());
      out.write("\r\n");
      out.write("									</a>\r\n");
      out.write("   \r\n");
      out.write("                                </section>\r\n");
      out.write("\r\n");
      out.write("                            </section>\r\n");
      out.write("\r\n");
      out.write("                            <section class=\"TitlesNames\">\r\n");
      out.write("                            \r\n");
      out.write("                                <h3>Description:</h3>\r\n");
      out.write("\r\n");
      out.write("                                <p class=\"TextDescription\">\r\n");
      out.write("                                    ");
      out.print(listAllArtsArtist.get(i).getDescription());
      out.write("\r\n");
      out.write("                                </p>\r\n");
      out.write("\r\n");
      out.write("                            </section>\r\n");
      out.write("\r\n");
      out.write("                            <section class=\"TitlesNames\">\r\n");
      out.write("                            \r\n");
      out.write("                                EXHIBITION DATE:\r\n");
      out.write("\r\n");
      out.write("                                <section class=\"Data\">\r\n");
      out.write("                           		    ");

                           		    dataDeExposicao = (listAllArtsArtist.get(i).getDataDeExposicao() == null) ? "" : listAllArtsArtist.get(i).getDataDeExposicao(); 
                           		 	
                           			out.print(dataDeExposicao);
                           		 	
      out.write("\r\n");
      out.write("                                </section>\r\n");
      out.write("\r\n");
      out.write("                            </section>\r\n");
      out.write("\r\n");
      out.write("                            <section class=\"TitlesNames\">\r\n");
      out.write("                            \r\n");
      out.write("                                PUBLICATION DATE:\r\n");
      out.write("\r\n");
      out.write("                                <section class=\"Data\">\r\n");
      out.write("                               		");

                           			dataDePublicacao = (listAllArtsArtist.get(i).getDataDePublicacao() == null) ? "" : listAllArtsArtist.get(i).getDataDePublicacao(); 
                           		 	
                       				out.print(dataDePublicacao);
                       		 		
      out.write("\r\n");
      out.write("                                </section>\r\n");
      out.write("\r\n");
      out.write("                            </section>\r\n");
      out.write("\r\n");
      out.write("                            <section class=\"TitlesNames\">\r\n");
      out.write("                            \r\n");
      out.write("                                PARTICIPATING ARTIST:\r\n");
      out.write("\r\n");
      out.write("                                <section class=\"Names\">\r\n");
      out.write("\r\n");
      out.write("                                    <a href=\"artist?idartist=\">\r\n");
      out.write("                               			Artist 01\r\n");
      out.write("									</a>\r\n");
      out.write("\r\n");
      out.write("                                </section>\r\n");
      out.write("\r\n");
      out.write("                            </section>\r\n");
      out.write("\r\n");
      out.write("                        </section>\r\n");
      out.write("\r\n");
      out.write("                    </section>\r\n");
      out.write("					\r\n");
      out.write("					");
} 
      out.write("	\r\n");
      out.write("					\r\n");
      out.write("					<!-- ART -->\r\n");
      out.write(" 										\r\n");
      out.write("                </section>\r\n");
      out.write("\r\n");
      out.write("            </section>\r\n");
      out.write("\r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("        <section id=\"info\">\r\n");
      out.write("\r\n");
      out.write("            Dev - Paulo de Tasso <br>\r\n");
      out.write("            Senior Full Stack Developer <br>\r\n");
      out.write("            World of digital artists - WODA®\r\n");
      out.write("\r\n");
      out.write("            <img class=\"ImagesButtons\" src=\"images/icons/SUPORTE01.png\" alt=\"\">\r\n");
      out.write("\r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("    </body>\r\n");
      out.write("\r\n");
      out.write("    <!--  \r\n");
      out.write("    <div class=\"load\">\r\n");
      out.write("        <div class=\"dot\"></div>\r\n");
      out.write("        <div class=\"dot\"></div>\r\n");
      out.write("        <div class=\"dot\"></div>\r\n");
      out.write("        <div class=\"dot\"></div>\r\n");
      out.write("        <div class=\"dot\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("    -->\r\n");
      out.write("\r\n");
      out.write("    <footer>\r\n");
      out.write("\r\n");
      out.write("        <section id=\"sectionFooter\">\r\n");
      out.write("\r\n");
      out.write("            World of digital artists - WODA®\r\n");
      out.write("\r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"js/artist.js\">\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"js/validator.js\">\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write(" 	<script src=\"js/home.js\">\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
