/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.68
 * Generated at: 2022-11-11 00:39:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class artistregister_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html id=\"html5\" lang=\"en-US\">\r\n");
      out.write("\r\n");
      out.write("    <head>\r\n");
      out.write("\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/register.css\" />\r\n");
      out.write("\r\n");
      out.write("        <title>WODA</title>\r\n");
      out.write("\r\n");
      out.write("        <link rel=\"icon\" href=\"images/logos/LogoWODA2.png\" type=\"image/gif\">\r\n");
      out.write("\r\n");
      out.write("    </head>\r\n");
      out.write("\r\n");
      out.write("    <!-- \r\n");
      out.write("    <section id=\"statusSistema\">\r\n");
      out.write("\r\n");
      out.write("    </section>\r\n");
      out.write("     -->\r\n");
      out.write("\r\n");
      out.write("    <header>\r\n");
      out.write("\r\n");
      out.write("        <section id=\"sectionMenu\">\r\n");
      out.write("\r\n");
      out.write("            <section id=\"sectionButtons\">\r\n");
      out.write("\r\n");
      out.write("                <button type=\"button\" id=\"seacherButton\" class=\"ButtonsRegister\">\r\n");
      out.write("\r\n");
      out.write("                    <img class=\"ImagesButtons\" src=\"images/icons/voltar.png\" alt=\"\" onclick=\"openPage('main', '_self')\">\r\n");
      out.write("\r\n");
      out.write("                </button>\r\n");
      out.write("\r\n");
      out.write("                <button type=\"button\" id=\"infoButton\" class=\"ButtonsRegister\">\r\n");
      out.write("\r\n");
      out.write("                    <img class=\"ImagesButtons\" src=\"images/icons/info.png\" alt=\"\"\r\n");
      out.write("                        onclick=\"openClose(info,'display','menuInfo')\">\r\n");
      out.write("\r\n");
      out.write("                </button>\r\n");
      out.write("\r\n");
      out.write("            </section>\r\n");
      out.write("\r\n");
      out.write("            <section id=\"sectionMenuButton\">\r\n");
      out.write("\r\n");
      out.write("                <button type=\"button\" id=\"buttonMenu\">\r\n");
      out.write("\r\n");
      out.write("                    <img id=\"imagemButtonMenu\" src=\"images/icons/menu01.png\" alt=\"\"\r\n");
      out.write("                        onclick=\"openClose(sectionButtons,'visibility')\">\r\n");
      out.write("\r\n");
      out.write("                </button>\r\n");
      out.write("\r\n");
      out.write("            </section>\r\n");
      out.write("\r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <body>\r\n");
      out.write("\r\n");
      out.write("        <form id=\"formRegisterArtist\" name=\"formregisterartist\" action=\"insert\" method=\"get\" onreset=\"clear()\">\r\n");
      out.write("\r\n");
      out.write("            <fieldset>\r\n");
      out.write("\r\n");
      out.write("                <legend class=\"LegendResgiter\">\r\n");
      out.write("\r\n");
      out.write("                    <img class=\"Buttons\" src=\"images/icons/ARTIST01.png\" alt=\"\">\r\n");
      out.write("\r\n");
      out.write("                    <img class=\"Buttons\" src=\"images/icons/ARTIST02.png\" alt=\"\">\r\n");
      out.write("\r\n");
      out.write("                </legend>\r\n");
      out.write("\r\n");
      out.write("                <table>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>\r\n");
      out.write("\r\n");
      out.write("                            <input type=\"text\" name=\"name\" maxlength=\"60\" size='65' placeholder=\"Name\"\r\n");
      out.write("                                onchange=\"verificarNome(this.value)\" required>\r\n");
      out.write("\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <div id=\"msgName\" class=\"AlertMsgs\">\r\n");
      out.write("                                *\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>\r\n");
      out.write("\r\n");
      out.write("                            <input type=\"email\" name=\"email\" onchange=\"validacaoEmail(formRegister.email)\"\r\n");
      out.write("                                maxlength=\"60\" size='65' placeholder=\"E-mail\">\r\n");
      out.write("\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <div id=\"msgEmail\" class=\"AlertMsgs\">\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>\r\n");
      out.write("\r\n");
      out.write("                            <select name=\"gender\" onchange=\"verificarGenero(this.value)\">\r\n");
      out.write("\r\n");
      out.write("                                <option value=\"gender\" selected>...Gender...</option>\r\n");
      out.write("\r\n");
      out.write("                                <option value=\"MALE\">\r\n");
      out.write("                                    MALE\r\n");
      out.write("                                </option>\r\n");
      out.write("\r\n");
      out.write("                                <option value=\"FEMALE\">\r\n");
      out.write("                                    FEMALE\r\n");
      out.write("                                </option>\r\n");
      out.write("\r\n");
      out.write("                                <option value=\"OTHER\">\r\n");
      out.write("                                    OTHER\r\n");
      out.write("                                </option>\r\n");
      out.write("\r\n");
      out.write("                            </select>\r\n");
      out.write("\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <div id=\"msgGender\" class=\"AlertMsgs\">\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>\r\n");
      out.write("\r\n");
      out.write("                            <input type=\"text\" name=\"birthday\" id=\"birthday\" placeholder=\"...Birthday...\"\r\n");
      out.write("                                onfocus=\"(this.type='date')\" onchange=\"validateDate('birthday',msgBirthday)\" required>\r\n");
      out.write("\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <div id=\"msgBirthday\" class=\"AlertMsgs\">\r\n");
      out.write("                                *\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>\r\n");
      out.write("\r\n");
      out.write("                            <select id=\"nationality\" name=\"nationality\" onchange=\"verificarNacionalidade(this.value)\"\r\n");
      out.write("                                required>\r\n");
      out.write("\r\n");
      out.write("                                <option value=\"nationality\" selected>...Nationality...</option>\r\n");
      out.write("                                <option value=\"África do Sul\">África do Sul</option>\r\n");
      out.write("                                <option value=\"Albânia\">Albânia</option>\r\n");
      out.write("                                <option value=\"Alemanha\">Alemanha</option>\r\n");
      out.write("                                <option value=\"Andorra\">Andorra</option>\r\n");
      out.write("                                <option value=\"Angola\">Angola</option>\r\n");
      out.write("                                <option value=\"Anguilla\">Anguilla</option>\r\n");
      out.write("                                <option value=\"Antigua\">Antigua</option>\r\n");
      out.write("                                <option value=\"Arábia Saudita\">Arábia Saudita</option>\r\n");
      out.write("                                <option value=\"Argentina\">Argentina</option>\r\n");
      out.write("                                <option value=\"Armênia\">Armênia</option>\r\n");
      out.write("                                <option value=\"Aruba\">Aruba</option>\r\n");
      out.write("                                <option value=\"Austrália\">Austrália</option>\r\n");
      out.write("                                <option value=\"Áustria\">Áustria</option>\r\n");
      out.write("                                <option value=\"Azerbaijão\">Azerbaijão</option>\r\n");
      out.write("                                <option value=\"Bahamas\">Bahamas</option>\r\n");
      out.write("                                <option value=\"Bahrein\">Bahrein</option>\r\n");
      out.write("                                <option value=\"Bangladesh\">Bangladesh</option>\r\n");
      out.write("                                <option value=\"Barbados\">Barbados</option>\r\n");
      out.write("                                <option value=\"Bélgica\">Bélgica</option>\r\n");
      out.write("                                <option value=\"Benin\">Benin</option>\r\n");
      out.write("                                <option value=\"Bermudas\">Bermudas</option>\r\n");
      out.write("                                <option value=\"Botsuana\">Botsuana</option>\r\n");
      out.write("                                <option value=\"Brasil\">Brasil</option>\r\n");
      out.write("                                <option value=\"Brunei\">Brunei</option>\r\n");
      out.write("                                <option value=\"Bulgária\">Bulgária</option>\r\n");
      out.write("                                <option value=\"Burkina Fasso\">Burkina Fasso</option>\r\n");
      out.write("                                <option value=\"Cabo Verde\">Cabo Verde</option>\r\n");
      out.write("                                <option value=\"Camarões\">Camarões</option>\r\n");
      out.write("                                <option value=\"Camboja\">Camboja</option>\r\n");
      out.write("                                <option value=\"Canadá\">Canadá</option>\r\n");
      out.write("                                <option value=\"Cazaquistão\">Cazaquistão</option>\r\n");
      out.write("                                <option value=\"Chade\">Chade</option>\r\n");
      out.write("                                <option value=\"Chile\">Chile</option>\r\n");
      out.write("                                <option value=\"China\">China</option>\r\n");
      out.write("                                <option value=\"Cidade do Vaticano\">Cidade do Vaticano</option>\r\n");
      out.write("                                <option value=\"Colômbia\">Colômbia</option>\r\n");
      out.write("                                <option value=\"Congo\">Congo</option>\r\n");
      out.write("                                <option value=\"Coréia do Sul\">Coréia do Sul</option>\r\n");
      out.write("                                <option value=\"Costa do Marfim\">Costa do Marfim</option>\r\n");
      out.write("                                <option value=\"Costa Rica\">Costa Rica</option>\r\n");
      out.write("                                <option value=\"Croácia\">Croácia</option>\r\n");
      out.write("                                <option value=\"Dinamarca\">Dinamarca</option>\r\n");
      out.write("                                <option value=\"Djibuti\">Djibuti</option>\r\n");
      out.write("                                <option value=\"Dominica\">Dominica</option>\r\n");
      out.write("                                <option value=\"EUA\">EUA</option>\r\n");
      out.write("                                <option value=\"Egito\">Egito</option>\r\n");
      out.write("                                <option value=\"El Salvador\">El Salvador</option>\r\n");
      out.write("                                <option value=\"Emirados Árabes\">Emirados Árabes</option>\r\n");
      out.write("                                <option value=\"Equador\">Equador</option>\r\n");
      out.write("                                <option value=\"Eritréia\">Eritréia</option>\r\n");
      out.write("                                <option value=\"Escócia\">Escócia</option>\r\n");
      out.write("                                <option value=\"Eslováquia\">Eslováquia</option>\r\n");
      out.write("                                <option value=\"Eslovênia\">Eslovênia</option>\r\n");
      out.write("                                <option value=\"Espanha\">Espanha</option>\r\n");
      out.write("                                <option value=\"Estônia\">Estônia</option>\r\n");
      out.write("                                <option value=\"Etiópia\">Etiópia</option>\r\n");
      out.write("                                <option value=\"Fiji\">Fiji</option>\r\n");
      out.write("                                <option value=\"Filipinas\">Filipinas</option>\r\n");
      out.write("                                <option value=\"Finlândia\">Finlândia</option>\r\n");
      out.write("                                <option value=\"França\">França</option>\r\n");
      out.write("                                <option value=\"Gabão\">Gabão</option>\r\n");
      out.write("                                <option value=\"Gâmbia\">Gâmbia</option>\r\n");
      out.write("                                <option value=\"Gana\">Gana</option>\r\n");
      out.write("                                <option value=\"Geórgia\">Geórgia</option>\r\n");
      out.write("                                <option value=\"Gibraltar\">Gibraltar</option>\r\n");
      out.write("                                <option value=\"Granada\">Granada</option>\r\n");
      out.write("                                <option value=\"Grécia\">Grécia</option>\r\n");
      out.write("                                <option value=\"Guadalupe\">Guadalupe</option>\r\n");
      out.write("                                <option value=\"Guam\">Guam</option>\r\n");
      out.write("                                <option value=\"Guatemala\">Guatemala</option>\r\n");
      out.write("                                <option value=\"Guiana\">Guiana</option>\r\n");
      out.write("                                <option value=\"Guiana Francesa\">Guiana Francesa</option>\r\n");
      out.write("                                <option value=\"Guiné-bissau\">Guiné-bissau</option>\r\n");
      out.write("                                <option value=\"Haiti\">Haiti</option>\r\n");
      out.write("                                <option value=\"Holanda\">Holanda</option>\r\n");
      out.write("                                <option value=\"Honduras\">Honduras</option>\r\n");
      out.write("                                <option value=\"Hong Kong\">Hong Kong</option>\r\n");
      out.write("                                <option value=\"Hungria\">Hungria</option>\r\n");
      out.write("                                <option value=\"Iêmen\">Iêmen</option>\r\n");
      out.write("                                <option value=\"Ilhas Cayman\">Ilhas Cayman</option>\r\n");
      out.write("                                <option value=\"Ilhas Cook\">Ilhas Cook</option>\r\n");
      out.write("                                <option value=\"Ilhas Curaçao\">Ilhas Curaçao</option>\r\n");
      out.write("                                <option value=\"Ilhas Marshall\">Ilhas Marshall</option>\r\n");
      out.write("                                <option value=\"Ilhas Turks &#038; Caicos\">Ilhas Turks e Caicos</option>\r\n");
      out.write("                                <option value=\"Ilhas Virgens (brit.)\">Ilhas Virgens (brit.)</option>\r\n");
      out.write("                                <option value=\"Ilhas Virgens(amer.)\">Ilhas Virgens(amer.)</option>\r\n");
      out.write("                                <option value=\"Ilhas Wallis e Futuna\">Ilhas Wallis e Futuna</option>\r\n");
      out.write("                                <option value=\"Índia\">Índia</option>\r\n");
      out.write("                                <option value=\"Indonésia\">Indonésia</option>\r\n");
      out.write("                                <option value=\"Inglaterra\">Inglaterra</option>\r\n");
      out.write("                                <option value=\"Irlanda\">Irlanda</option>\r\n");
      out.write("                                <option value=\"Islândia\">Islândia</option>\r\n");
      out.write("                                <option value=\"Israel\">Israel</option>\r\n");
      out.write("                                <option value=\"Itália\">Itália</option>\r\n");
      out.write("                                <option value=\"Jamaica\">Jamaica</option>\r\n");
      out.write("                                <option value=\"Japão\">Japão</option>\r\n");
      out.write("                                <option value=\"Jordânia\">Jordânia</option>\r\n");
      out.write("                                <option value=\"Kuwait\">Kuwait</option>\r\n");
      out.write("                                <option value=\"Latvia\">Latvia</option>\r\n");
      out.write("                                <option value=\"Líbano\">Líbano</option>\r\n");
      out.write("                                <option value=\"Liechtenstein\">Liechtenstein</option>\r\n");
      out.write("                                <option value=\"Lituânia\">Lituânia</option>\r\n");
      out.write("                                <option value=\"Luxemburgo\">Luxemburgo</option>\r\n");
      out.write("                                <option value=\"Macau\">Macau</option>\r\n");
      out.write("                                <option value=\"Macedônia\">Macedônia</option>\r\n");
      out.write("                                <option value=\"Madagascar\">Madagascar</option>\r\n");
      out.write("                                <option value=\"Malásia\">Malásia</option>\r\n");
      out.write("                                <option value=\"Malaui\">Malaui</option>\r\n");
      out.write("                                <option value=\"Mali\">Mali</option>\r\n");
      out.write("                                <option value=\"Malta\">Malta</option>\r\n");
      out.write("                                <option value=\"Marrocos\">Marrocos</option>\r\n");
      out.write("                                <option value=\"Martinica\">Martinica</option>\r\n");
      out.write("                                <option value=\"Mauritânia\">Mauritânia</option>\r\n");
      out.write("                                <option value=\"Mauritius\">Mauritius</option>\r\n");
      out.write("                                <option value=\"México\">México</option>\r\n");
      out.write("                                <option value=\"Moldova\">Moldova</option>\r\n");
      out.write("                                <option value=\"Mônaco\">Mônaco</option>\r\n");
      out.write("                                <option value=\"Montserrat\">Montserrat</option>\r\n");
      out.write("                                <option value=\"Nepal\">Nepal</option>\r\n");
      out.write("                                <option value=\"Nicarágua\">Nicarágua</option>\r\n");
      out.write("                                <option value=\"Niger\">Niger</option>\r\n");
      out.write("                                <option value=\"Nigéria\">Nigéria</option>\r\n");
      out.write("                                <option value=\"Noruega\">Noruega</option>\r\n");
      out.write("                                <option value=\"Nova Caledônia\">Nova Caledônia</option>\r\n");
      out.write("                                <option value=\"Nova Zelândia\">Nova Zelândia</option>\r\n");
      out.write("                                <option value=\"Omã\">Omã</option>\r\n");
      out.write("                                <option value=\"Palau\">Palau</option>\r\n");
      out.write("                                <option value=\"Panamá\">Panamá</option>\r\n");
      out.write("                                <option value=\"Papua-nova Guiné\">Papua-nova Guiné</option>\r\n");
      out.write("                                <option value=\"Paquistão\">Paquistão</option>\r\n");
      out.write("                                <option value=\"Peru\">Peru</option>\r\n");
      out.write("                                <option value=\"Polinésia Francesa\">Polinésia Francesa</option>\r\n");
      out.write("                                <option value=\"Polônia\">Polônia</option>\r\n");
      out.write("                                <option value=\"Porto Rico\">Porto Rico</option>\r\n");
      out.write("                                <option value=\"Portugal\">Portugal</option>\r\n");
      out.write("                                <option value=\"Qatar\">Qatar</option>\r\n");
      out.write("                                <option value=\"Quênia\">Quênia</option>\r\n");
      out.write("                                <option value=\"Rep. Dominicana\">Rep. Dominicana</option>\r\n");
      out.write("                                <option value=\"Rep. Tcheca\">Rep. Tcheca</option>\r\n");
      out.write("                                <option value=\"Reunion\">Reunion</option>\r\n");
      out.write("                                <option value=\"Romênia\">Romênia</option>\r\n");
      out.write("                                <option value=\"Ruanda\">Ruanda</option>\r\n");
      out.write("                                <option value=\"Rússia\">Rússia</option>\r\n");
      out.write("                                <option value=\"Saipan\">Saipan</option>\r\n");
      out.write("                                <option value=\"Samoa Americana\">Samoa Americana</option>\r\n");
      out.write("                                <option value=\"Senegal\">Senegal</option>\r\n");
      out.write("                                <option value=\"Serra Leone\">Serra Leone</option>\r\n");
      out.write("                                <option value=\"Seychelles\">Seychelles</option>\r\n");
      out.write("                                <option value=\"Singapura\">Singapura</option>\r\n");
      out.write("                                <option value=\"Síria\">Síria</option>\r\n");
      out.write("                                <option value=\"Sri Lanka\">Sri Lanka</option>\r\n");
      out.write("                                <option value=\"St. Kitts &#038; Nevis\">St. Kitts E Nevis</option>\r\n");
      out.write("                                <option value=\"St. Lúcia\">St. Lúcia</option>\r\n");
      out.write("                                <option value=\"St. Vincent\">St. Vincent</option>\r\n");
      out.write("                                <option value=\"Sudão\">Sudão</option>\r\n");
      out.write("                                <option value=\"Suécia\">Suécia</option>\r\n");
      out.write("                                <option value=\"Suiça\">Suiça</option>\r\n");
      out.write("                                <option value=\"Suriname\">Suriname</option>\r\n");
      out.write("                                <option value=\"Tailândia\">Tailândia</option>\r\n");
      out.write("                                <option value=\"Taiwan\">Taiwan</option>\r\n");
      out.write("                                <option value=\"Tanzânia\">Tanzânia</option>\r\n");
      out.write("                                <option value=\"Togo\">Togo</option>\r\n");
      out.write("                                <option value=\"Trinidad &#038; Tobago\">Trinidad E Tobago</option>\r\n");
      out.write("                                <option value=\"Tunísia\">Tunísia</option>\r\n");
      out.write("                                <option value=\"Turquia\">Turquia</option>\r\n");
      out.write("                                <option value=\"Ucrânia\">Ucrânia</option>\r\n");
      out.write("                                <option value=\"Uganda\">Uganda</option>\r\n");
      out.write("                                <option value=\"Uruguai\">Uruguai</option>\r\n");
      out.write("                                <option value=\"Venezuela\">Venezuela</option>\r\n");
      out.write("                                <option value=\"Vietnã\">Vietnã</option>\r\n");
      out.write("                                <option value=\"Zaire\">Zaire</option>\r\n");
      out.write("                                <option value=\"Zâmbia\">Zâmbia</option>\r\n");
      out.write("                                <option value=\"Zimbábue\">Zimbábue</option>\r\n");
      out.write("\r\n");
      out.write("                            </select>\r\n");
      out.write("\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <div id=\"msgNationality\" class=\"AlertMsgs\">\r\n");
      out.write("                                *\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("\r\n");
      out.write("                    <tr id=\"sectionCpf\">\r\n");
      out.write("                        <td>\r\n");
      out.write("\r\n");
      out.write("                            <input type=\"text\" id=\"cpf\" name=\"cpf\" onchange=\"formatarCpf()\" maxlength=\"11\" size='11'\r\n");
      out.write("                                placeholder=\"CPF\" required>\r\n");
      out.write("\r\n");
      out.write("                        </td>\r\n");
      out.write("\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <div id=\"msgCpf\" class=\"AlertMsgs\">\r\n");
      out.write("                                *\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </td>\r\n");
      out.write("\r\n");
      out.write("                    </tr>\r\n");
      out.write("\r\n");
      out.write("                    <tr>\r\n");
      out.write("\r\n");
      out.write("                        <td>\r\n");
      out.write("\r\n");
      out.write("                            <br>\r\n");
      out.write("                           \r\n");
      out.write("                           ");
  
      out.write("\r\n");
      out.write("                           \r\n");
      out.write("                           <!--  <input id=\"fileInputArtist\" name=\"inputfile\" type=\"file\" accept=\"image/*\" /> -->\r\n");
      out.write("                           \r\n");
      out.write("                           \r\n");
      out.write("                            <br>\r\n");
      out.write("\r\n");
      out.write("                            <output id=\"listArtist\" class=\"lists\">\r\n");
      out.write("\r\n");
      out.write("                                File:\r\n");
      out.write("\r\n");
      out.write("                            </output>\r\n");
      out.write("\r\n");
      out.write("                        </td>\r\n");
      out.write("\r\n");
      out.write("                        <td>\r\n");
      out.write("\r\n");
      out.write("                            <div id=\"msgImageArtist\" class=\"AlertMsgs\">\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </td>\r\n");
      out.write("\r\n");
      out.write("                    </tr>\r\n");
      out.write("\r\n");
      out.write("                </table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <section class=\"SectionButtons\">\r\n");
      out.write("\r\n");
      out.write("                    <section id=\"msgStatus\" class=\"AlertMsgs\">\r\n");
      out.write("\r\n");
      out.write("                    </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <button type=\"reset\" class=\"Buttons\">\r\n");
      out.write("\r\n");
      out.write("                        <img class=\"ImagesButtonsRegister\" src=\"images/icons/LIMPAR.png\" alt=\"\">\r\n");
      out.write("\r\n");
      out.write("                    </button>\r\n");
      out.write("\r\n");
      out.write("                    <button type=\"submit\" id=\"submitButton\" class=\"Buttons\" onclick=\"validar('formRegisterArtist')\">\r\n");
      out.write("\r\n");
      out.write("                        <img class=\"ImagesButtonsRegister\" src=\"images/icons/save01.png\" alt=\"\">\r\n");
      out.write("\r\n");
      out.write("                    </button>\r\n");
      out.write("\r\n");
      out.write("                </section>\r\n");
      out.write("\r\n");
      out.write("            </fieldset>\r\n");
      out.write("\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("        <section id=\"info\">\r\n");
      out.write("\r\n");
      out.write("            Dev - Paulo de Tasso <br>\r\n");
      out.write("            Senior Full Stack Developer <br>\r\n");
      out.write("            World of digital artists - WODA®\r\n");
      out.write("\r\n");
      out.write("            <img class=\"ImagesButtons\" src=\"images/icons/SUPORTE01.png\" alt=\"\">\r\n");
      out.write("\r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("    </body>\r\n");
      out.write("\r\n");
      out.write("    <!--  \r\n");
      out.write("\r\n");
      out.write("    <div class=\"load\">\r\n");
      out.write("        <div class=\"dot\"></div>\r\n");
      out.write("        <div class=\"dot\"></div>\r\n");
      out.write("        <div class=\"dot\"></div>\r\n");
      out.write("        <div class=\"dot\"></div>\r\n");
      out.write("        <div class=\"dot\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("    -->\r\n");
      out.write("\r\n");
      out.write("    <footer>\r\n");
      out.write("\r\n");
      out.write("        <section id=\"sectionFooter\">\r\n");
      out.write("\r\n");
      out.write("            World of digital artists - WODA®\r\n");
      out.write("\r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"js/home.js\">\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"js/validator.js\">\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
